#!/bin/sh
TERMINUSDB_SERVER_MODE=${TERMINUSDB_SERVER_MODE:-attach}
TERMINUSDB_SERVER_NAME=${TERMINUSDB_SERVER_NAME:-localhost}
TERMINUSDB_ADMIN_PASS=${TERMINUSDB_ADMIN_PASS:-root}
TERMINUSDB_SERVER_PORT=${TERMINUSDB_SERVER_PORT:-6363}
TERMINUSDB_SERVER_PUBLIC_URL=${TERMINUSDB_SERVER_PUBLIC_URL:-"http://localhost:6363"}
TERMINUSDB_AUTOATTACH=${TERMINUSDB_AUTOATTACH:-true}
TERMINUSDB_AUTOLOGIN=${TERMINUSDB_AUTOLOGIN:-false}
TERMINUSDB_ENABLE_WELCOME_SCREEN=${TERMINUSDB_ENABLE_WELCOME_SCREEN:-false}

if [ ! -d /app/terminusdb/storage/db ] && [ "$TERMINUSDB_ENABLE_WELCOME_SCREEN" = false ]; then
    /app/terminusdb/utils/db_init -s "$TERMINUSDB_SERVER_NAME" -k "$TERMINUSDB_ADMIN_PASS" --port "$TERMINUSDB_SERVER_PORT" --public_url "$TERMINUSDB_SERVER_PUBLIC_URL" --autologin="$TERMINUSDB_AUTOLOGIN" --autoattach="$TERMINUSDB_AUTOATTACH"
elif [ "$TERMINUSDB_ENABLE_WELCOME_SCREEN" = false ]; then
    /app/terminusdb/utils/db_init -s "$TERMINUSDB_SERVER_NAME" -k "$TERMINUSDB_ADMIN_PASS" --port "$TERMINUSDB_SERVER_PORT" --public_url "$TERMINUSDB_SERVER_PUBLIC_URL" --autologin="$TERMINUSDB_AUTOLOGIN" --autoattach="$TERMINUSDB_AUTOATTACH" --only-config
fi

if [ "$TERMINUSDB_ENABLE_WELCOME_SCREEN" = true ]; then
    cd /app/terminusdb/utils && swipl welcome_screen.pl $TERMINUSDB_SERVER_PORT
fi

echo "SERVER_MODE $TERMINUSDB_SERVER_MODE"
echo "SERVER_NAME $TERMINUSDB_SERVER_NAME"
echo "SERVER_PORT $TERMINUSDB_SERVER_PORT"
echo "PUBLIC_URL $TERMINUSDB_SERVER_PUBLIC_URL"
echo "AUTO_ATTACH $TERMINUSDB_AUTOATTACH"
echo "AUTO_LOGIN $TERMINUSDB_AUTOLOGIN"
echo "ENABLE_WELCOME_SCREEN $TERMINUSDB_ENABLE_WELCOME_SCREEN"
/app/terminusdb/start.pl "$TERMINUSDB_SERVER_MODE"

