#!/bin/sh
TERMINUS_SERVER_MODE=${TERMINUS_SERVER_MODE:-attach}
TERMINUS_SERVER_NAME=${TERMINUS_SERVER_NAME:-localhost}
TERMINUS_ADMIN_PASS=${TERMINUS_ADMIN_PASS:-root}
TERMINUS_SERVER_PORT=${TERMINUS_SERVER_PORT:-6363}
TERMINUS_SERVER_PUBLIC_URL=${TERMINUS_SERVER_PUBLIC_URL:-"http://localhost:6363"}
TERMINUS_AUTOATTACH=${TERMINUS_AUTOATTACH:-true}
TERMINUS_AUTOLOGIN=${TERMINUS_AUTOLOGIN:-false}
TERMINUS_ENABLE_WELCOME_SCREEN=${TERMINUS_ENABLE_WELCOME_SCREEN:-false}

if [ ! -f /app/terminusdb/storage/prefix.db ] && [ "$TERMINUS_ENABLE_WELCOME_SCREEN" = false ]; then
    /app/terminusdb/utils/db_util -s "$TERMINUS_SERVER_NAME" -k "$TERMINUS_ADMIN_PASS" --port "$TERMINUS_SERVER_PORT" --public_url "$TERMINUS_SERVER_PUBLIC_URL" --autologin="$TERMINUS_AUTOLOGIN" --autoattach="$TERMINUS_AUTOATTACH"
elif [ "$TERMINUS_ENABLE_WELCOME_SCREEN" = false ]; then
    /app/terminusdb/utils/db_util -s "$TERMINUS_SERVER_NAME" -k "$TERMINUS_ADMIN_PASS" --port "$SERVER_PORT" --public_url "$TERMINUS_SERVER_PUBLIC_URL" --autologin="$TERMINUS_AUTOLOGIN" --autoattach="$TERMINUS_AUTOATTACH" --only-config
fi

if [ "$TERMINUS_ENABLE_WELCOME_SCREEN" = true ]; then
    cd /app/terminusdb/utils && swipl welcome_screen.pl $TERMINUS_SERVER_PORT
fi

echo "SERVER_MODE $TERMINUS_SERVER_MODE"
echo "SERVER_NAME $TERMINUS_SERVER_NAME"
echo "SERVER_PORT $TERMINUS_SERVER_PORT"
echo "PUBLIC_URL $TERMINUS_SERVER_PUBLIC_URL"
echo "AUTO_ATTACH $TERMINUS_AUTOATTACH"
echo "AUTO_LOGIN $TERMINUS_AUTOLOGIN"
echo "ENABLE_WELCOME_SCREEN $TERMINUS_ENABLE_WELCOME_SCREEN"
/app/terminusdb/start.pl "$TERMINUS_SERVER_MODE"

