#!/bin/sh
TERMINUSDB_SERVER_NAME=${TERMINUSDB_SERVER_NAME:-localhost}
TERMINUSDB_ADMIN_PASS=${TERMINUSDB_ADMIN_PASS:-root}
TERMINUSDB_SERVER_PORT=${TERMINUSDB_SERVER_PORT:-6363}
TERMINUSDB_AUTOATTACH=${TERMINUSDB_AUTOATTACH:-true}
TERMINUSDB_AUTOLOGIN=${TERMINUSDB_AUTOLOGIN:-false}
TERMINUSDB_ENABLE_WELCOME_SCREEN=${TERMINUSDB_ENABLE_WELCOME_SCREEN:-false}

if [ ! -d /app/terminusdb/storage/db ] && [ "$TERMINUSDB_ENABLE_WELCOME_SCREEN" = false ]; then
    /app/terminusdb/start.pl store init -s "$TERMINUSDB_SERVER_NAME" -k "$TERMINUSDB_ADMIN_PASS" --port "$TERMINUSDB_SERVER_PORT" --autologin="$TERMINUSDB_AUTOLOGIN" --autoattach="$TERMINUSDB_AUTOATTACH"
fi

if [ "$TERMINUSDB_ENABLE_WELCOME_SCREEN" = true ]; then
    cd /app/terminusdb/utils && swipl welcome_screen.pl $TERMINUSDB_SERVER_PORT
fi

echo "SERVER_NAME $TERMINUSDB_SERVER_NAME"
echo "SERVER_PORT $TERMINUSDB_SERVER_PORT"
echo "AUTO_ATTACH $TERMINUSDB_AUTOATTACH"
echo "AUTO_LOGIN $TERMINUSDB_AUTOLOGIN"
echo "ENABLE_WELCOME_SCREEN $TERMINUSDB_ENABLE_WELCOME_SCREEN"
swipl --tty=false /app/terminusdb/start.pl serve --interactive

