#!/bin/sh

if ! type rdf2hdt > /dev/null; then
	printf "We can't proceed without rdf2hdt but it's not installed.  Aborting.\n";
	exit 1;
fi

if ! type swipl > /dev/null; then
	printf "We can't proceed without swipl but it's not installed.  Aborting.\n";
	exit 1;
fi

usage="$(basename "$0") [-h] [-k KEY] -- program to set admin KEY

where:
    -h  show this help text
    KEY set the admin key value"

# Get the current script directory
dir=$(dirname "$0")

# The database to update
examplettl="$dir/../storage/http%3a%2f%2flocalhost%2fcapability/main/1/1-ckp-example.ttl"
instancettl="$dir/../storage/http%3a%2f%2flocalhost%2fcapability/main/1/1-ckp.ttl"
instancedb="$dir/../storage/http%3a%2f%2flocalhost%2fcapability/main/1/1-ckp.hdt"

while getopts ':hk:' option; do
  case "$option" in
    h) echo "$usage"
       exit
       ;;
    k) KEY=${OPTARG}
	   HASH=$(swipl -g "use_module(library(md5)),md5_hash($KEY,Res,[]),write(Res),nl,halt.")
	   cp "$examplettl" "$instancettl";
	   sed -i "s/SEKRET_ADMIN_KEY/$HASH/" "$instancettl";
	   rdf2hdt "$instancettl" "$instancedb";
	   rm "$instancedb.index.*";
	   printf "Key updated\n" >&2
       ;;
    *) printf "missing argument for -%s\n" "$OPTARG" >&2
       echo "$usage" >&2
       exit 1
       ;;
  esac
done
shift $((OPTIND - 1))
